### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by mikhailnov**
By victorr2007

### CODE REVIEW

**Comment by u8sand** [comment]
@mikhailnov I'll love to merge your translation and add you as a contributor. I'm trying to understand the "By victorr2007" is this another person or is this your desired alias in the credits?

**Comment by mikhailnov** [comment]
It is another person

**Comment by mikhailnov** [comment]
ping

**Comment by u8sand** [comment]
@mikhailnov thanks again for your contribution. Your translation was merged along with several others

**Comment by mikhailnov** [comment]
Thanks!

**Pull request closed without merging**
